resources:
  - name: src
    type: git
    source:
      uri: https://github.com/ewirch/concourse-test.git

jobs:
  - name: build backend
    plan:
      - get: src
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: busybox
          inputs:
            - name: src
          run:
            path: src/build.sh
          outputs:
            - name: out
      - aggregate:
          - task: test backend
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: busybox
              inputs:
                - name: src
                - name: out
              run:
                path: cat
                args: ['out/build-out']
          - task: package backend
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: busybox
              inputs:
                - name: src
                - name: out
              run:
                path: src/package.sh
              outputs:
                - name: package
