resources:
  - name: src
    type: git
    source:
      uri: https://github.com/ewirch/concourse-test.git

jobs:
  - name: build backend
    plan:
      - get: src
        trigger: true
      - task: run fly
        file: src/concourse-fly.yml
